application: actuarize
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
  


handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /images
  static_dir: images
  
- url: /stylesheets
  static_dir: stylesheets  
  
- url: /scripts
  static_dir: scripts
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /.*
  script: main.app